---
- name: Test
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    kubernetes_namespace: test-namespace
  tasks:
    - name: Create secret
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: api-token
            namespace: '{{ kubernetes_namespace }}'
          type: Opaque
        wait: true
      tags:
        - print_action

- name: Test
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    kubernetes_namespace: test-namespace
  tasks:
    - name: Create K8s secrets
      vars:
        task_args:
          definition:
            apiVersion: v1
            kind: Secret
            metadata:
              name: api-token
              namespace: '{{ kubernetes_namespace }}'
            type: Opaque
          wait: true
      block:
        - name: List the 'kubernetes.core.k8s' arguments
          debug:
            var: task_args
            verbosity: 1

        - name: Create secret
          kubernetes.core.k8s: '{{ task_args }}'
