---
- name: Get DB details from tomcat xml
  hosts: localhost
  environment:
    ANSIBLE_COLLECTIONS_PATHS: "runner/requirements_collections"
  tasks:
    - name: Install general
      shell: ansible-galaxy collection install servicenow.servicenow --no-cache

- name: Get DB details from tomcat xml
  hosts: localhost
  environment:
    ANSIBLE_COLLECTIONS_PATHS: "runner/requirements_collections"
  tasks:
    - name: Try to invoke a ServiceNow task
      servicenow.servicenow.snow_record_find:
        username: ansible_test
        password: my_password
        instance: dev99999
        table: incident
        query:
          assignment_group: d625dccec0a8016700a222a0f7900d06
        return_fields:
          - number
          - opened_at
